### ISSUE TITLE
No. Please god no.

### ISSUE THREAD

**Issue by imflavio** [Wildhoney/ava-webcomponents#1]
Stop it, get some help

**Comment by Wildhoney** [comment]
I've seen the light.

**Comment by tylerkrett** [comment]
Im jewish and  and I am praying to Jesus for this not to happen. PLEASE JESUS NO PLEASE

**Comment by Wildhoney** [comment]
Real Jews love AVA.

**Comment by Wildhoney** [comment]
Real Portuguese love Web Components.

**Comment by imflavio** [comment]
I love the Web and I love Components, but Web Components? No thanks 😬

**Comment by tylerkrett** [comment]
Hhhhm Ava is completely free so I doubt that my people like this
